<?xml version="1.0" encoding="utf-8"?><Database Name="SCP" Class="BDDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=AIN-MSSRV\SISTEMASAIN;Initial Catalog=SCP;Persist Security Info=True;User ID=sa" SettingsObjectName="SCP.Properties.Settings" SettingsPropertyName="SCPConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.bultos" Member="bultos">
    <Type Name="bultos">
      <Column Name="id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="corte" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="bale" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="yds" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="noBulto" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ReleaseL" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ReleaseT" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="grupo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="oCaptura" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="lav" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.catCliente" Member="catCliente">
    <Type Name="catCliente">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.catEstilo" Member="catEstilo">
    <Type Name="catEstilo">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idTipoTela" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idProveedor" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="estilo" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="precio" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="existencia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="existenciaR" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.catPerfil" Member="catPerfil">
    <Type Name="catPerfil">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.catProveedor" Member="catProveedor">
    <Type Name="catProveedor">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.catTipoCierre" Member="catTipoCierre">
    <Type Name="catTipoCierre">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.catTipoSalida" Member="catTipoSalida">
    <Type Name="catTipoSalida">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="clave" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.catTipoTela" Member="catTipoTela">
    <Type Name="catTipoTela">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.catUbicacion" Member="catUbicacion">
    <Type Name="catUbicacion">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ubicacion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.catUsuario" Member="catUsuario">
    <Type Name="catUsuario">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idPerfil" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="contraseña" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.cierre" Member="cierre">
    <Type Name="cierre">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="fechaInicial" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="fechaFinal" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="idTipoCierre" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.corte" Member="corte">
    <Type Name="corte">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idCorteDetalle" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idPirDetallePO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="patt" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="SemanaCorte" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Tendedor" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="idPlanta" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="temporada" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="pares" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="issue" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="cleanUp" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="cutOnly" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="div" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="tc" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="paisTemporada" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Comentarios" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="DateIssue" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="fechaReciboTela" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="fechaCorte" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.corteDetalle" Member="corteDetalle">
    <Type Name="corteDetalle">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idCorte" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idEstilo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idPo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idEstado" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idTipo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="enviado" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Liberado" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Manta" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="avios" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="comun" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ancho" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="alto" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="foleo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="yield" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="loss" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="MKRYDS" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="actYds" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="actUnits" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="desperdicio" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="NoDefectosTela" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FechaEmarqueC" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="fechaTendido" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="fechaEmbarque" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="comentatios1" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="comentarioBale" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.corteDetalleSeccion" Member="corteDetalleSeccion">
    <Type Name="corteDetalleSeccion">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idCorte" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="mkb" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="length" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="idTalla" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[plan]" Member="plan" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="corteSeccion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="noSeccion" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tendedor" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="pares" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.corteDetalleTallasBultosxSeccion" Member="corteDetalleTallasBultosxSeccion">
    <Type Name="corteDetalleTallasBultosxSeccion">
      <Column Name="id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idCorte" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="mkb" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="idTalla" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="idBulto" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="par" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="bale" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.corteDetalleYardas" Member="corteDetalleYardas">
    <Type Name="corteDetalleYardas">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idRelease" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idReleaseLab" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idNoRollo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="yardas" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="grupo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="lavado" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.devolucion" Member="devolucion">
    <Type Name="devolucion">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idTipoTela" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Release" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="fechaHoy" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.devolucionDetalle" Member="devolucionDetalle">
    <Type Name="devolucionDetalle">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idDevolucion" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="idRollo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idTipoEntrada" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="longYardas" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.entradaTela" Member="entradaTela">
    <Type Name="entradaTela">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="release" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="idTipoTela" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idProveedor" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idCliente" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idEstilo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idUsuario" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="costo" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="ancho" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="po" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="camion" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="costoFlete" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="CostoImportacion" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="facturaAnterior" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="totalRollos" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="totalYardasRelease" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="estatus" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="fecha" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.entradaTelaDetalle" Member="entradaTelaDetalle">
    <Type Name="entradaTelaDetalle">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idEntradaTela" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idUbicacion" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="noRollo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="existencia" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="logMetros" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="entrada" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="totalExistenciaYDS" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="totalEntradaYDS" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="stiffness" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="onzas" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.localizaRollos" Member="localizaRollos">
    <Type Name="localizaRollos">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idRollo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="longMetros" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="idEntrada" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Release" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="existencia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="entrada" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="estatus" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.pir" Member="pir">
    <Type Name="pir">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idDivision" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idEstilo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idTemporada" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idLavado" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="pir" Member="pir1" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="yield" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="cantidadPair" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="fechaRecibido" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="fechaCorte" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="fechaUltimodiaCorte" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.pirDetallePO" Member="pirDetallePO">
    <Type Name="pirDetallePO">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idPir" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="po" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="unidadesPo" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="yield" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="fechaCorte" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="fechaxMexico" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="YDSRequeridas" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="fechaEnvioCliente" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="costo" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="[plan]" Member="plan" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.pirDetalleTela" Member="pirDetalleTela">
    <Type Name="pirDetalleTela">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idPir" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="telaProbada" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="estiloTela" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.salida" Member="salida">
    <Type Name="salida">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="salidaRollos" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idTipoSalida" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idTipoTela" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idCorte" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.salidaDetalle" Member="salidaDetalle">
    <Type Name="salidaDetalle">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idSalida" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="release" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="rollo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="yardas" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="idSecuencia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="totalRollos" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="totalYardas" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.ActualizaEntrada" Method="ActualizaEntrada">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="release" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="idTipoTela" Type="System.Int32" DbType="Int" />
    <Parameter Name="idProveedor" Type="System.Int32" DbType="Int" />
    <Parameter Name="idCliente" Type="System.Int32" DbType="Int" />
    <Parameter Name="idEstilo" Type="System.Int32" DbType="Int" />
    <Parameter Name="idEstatus" Type="System.Int32" DbType="Int" />
    <Parameter Name="costo" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="ancho" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="po" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="camion" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="costoFlete" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="CostoImportacion" Parameter="costoImportacion" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="facturaAnterior" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="totalRollos" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="totalYardasRelease" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="fecha" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="fechaModificacion" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="idUsuario_Modificacion" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.ActualizaEntradaDetalle" Method="ActualizaEntradaDetalle">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="idEntradaTela" Type="System.Int32" DbType="Int" />
    <Parameter Name="idUbicacion" Type="System.Int32" DbType="Int" />
    <Parameter Name="noRollo" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="existencia" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="logMetros" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="logYardas" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="entrada" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="totalExistenciaYDS" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="totalEntradaYDS" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="stiffness" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="onzas" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="idUsuario_Modificacion" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.BorrarEntrada" Method="BorrarEntrada">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="idUsuario_Borrado" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.BorrarEntradaDetalle" Method="BorrarEntradaDetalle">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="idUsuario_Borrado" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.ConsultaUsuario" Method="ConsultaUsuario">
    <Parameter Name="usuario" Type="System.String" DbType="VarChar(150)" />
    <Parameter Name="password" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="ConsultaUsuarioResult">
      <Column Name="nombre" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="perfil" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GuardarEntradaDetalle" Method="GuardarEntradaDetalle">
    <Parameter Name="idEntradaTela" Type="System.Int32" DbType="Int" />
    <Parameter Name="idUbicacion" Type="System.Int32" DbType="Int" />
    <Parameter Name="noRollo" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="existencia" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="logMetros" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="logYardas" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="entrada" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="totalExistenciaYDS" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="totalEntradaYDS" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="stiffness" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="onzas" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="idUsuario_Creacion" Type="System.Int32" DbType="Int" />
    <ElementType Name="GuardarEntradaDetalleResult">
      <Column Name="" Member="Column1" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GuardarEntrada" Method="GuardarEntrada">
    <Parameter Name="release" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="idTipoTela" Type="System.Int32" DbType="Int" />
    <Parameter Name="idProveedor" Type="System.Int32" DbType="Int" />
    <Parameter Name="idCliente" Type="System.Int32" DbType="Int" />
    <Parameter Name="idEstilo" Type="System.Int32" DbType="Int" />
    <Parameter Name="idEstatus" Type="System.Int32" DbType="Int" />
    <Parameter Name="costo" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="ancho" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="po" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="camion" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="costoFlete" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="CostoImportacion" Parameter="costoImportacion" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="facturaAnterior" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="totalRollos" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="totalYardasRelease" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="fecha" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="idUsuario_Creacion" Type="System.Int32" DbType="Int" />
    <ElementType Name="GuardarEntradaResult">
      <Column Name="" Member="Column1" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.ConsultaEntrada" Method="ConsultaEntrada">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <ElementType Name="ConsultaEntradaResult">
      <Column Name="release" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="idTipoTela" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idProveedor" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idCliente" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idEstilo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idEstatus" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="costo" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="ancho" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="po" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="camion" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="costoFlete" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="CostoImportacion" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="facturaAnterior" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="totalRollos" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="totalYardasRelease" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="fecha" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="idUsuario_Creacion" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.ConsultaCliente" Method="ConsultaCliente">
    <ElementType Name="ConsultaClienteResult">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.ConsultaUbicacion" Method="ConsultaUbicacion">
    <ElementType Name="ConsultaUbicacionResult">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.ConsultaEstatus" Method="ConsultaEstatus">
    <ElementType Name="ConsultaEstatusResult">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.ConsultaEstilo" Method="ConsultaEstilo">
    <ElementType Name="ConsultaEstiloResult">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idTipoTela" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idProveedor" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="precio" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="existencia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="existenciaR" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.ConsultaProveedor" Method="ConsultaProveedor">
    <ElementType Name="ConsultaProveedorResult">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.ConsultaTipoTela" Method="ConsultaTipoTela">
    <ElementType Name="ConsultaTipoTelaResult">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.ConsultaEntradaDetalle" Method="ConsultaEntradaDetalle">
    <Parameter Name="idEntradaTela" Type="System.Int32" DbType="Int" />
    <ElementType Name="ConsultaEntradaDetalleResult">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idEntradaTela" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idUbicacion" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="noRollo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="existencia" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="logMetros" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="logYardas" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="entrada" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="totalExistenciaYDS" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="totalEntradaYDS" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="stiffness" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="onzas" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="idUsuario_Creacion" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>